name: Merge

on:
  schedule: # Run every 3 hours
    - cron: "0 0,3,6,9,12,15,18,21 * * *"
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ensures the bot can push to the repository
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history and branches across the repo

      - name: Merge main into production
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Fetch and checkout production, then merge main into it
          git fetch origin production:production
          git checkout production
          git merge origin/main --no-ff -m "Automated merge: main into production"
          git push origin production
          
